Feat: update calico add compatibility to 1.29, release v1.16.1
sighupio/fury-kubernetes-networking pull request #79
Opened 2024-04-18 12:44 UTC by nutellinoit

This PR adds the support for kubernetes 1.29 and bumps calico to 3.27.3 and tigera operator to 1.32.7

Also, I added e2e tests for tigera operator, that was missing.

I also made the tests sequential, since the parallel execution was breaking too many times.

2024-04-18 13:16 UTC, ralgozino requested changes
- If we are changing the supported versions, wouldn't it be better to bump the module's minor version? (i.e. 1.7.0 instead of 1.6.1)
- The compatibility matrix needs to be updated too.
- I left some non-blocking suggestions

2024-04-18 13:16 UTC, ralgozino commented on katalog/tests/calico/tigera.sh
> +        kubectl apply -f 'https://raw.githubusercontent.com/sighupio/fury-kubernetes-monitoring/v2.0.1/katalog/prometheus-operator/crds/0prometheusruleCustomResourceDefinition.yaml'
these are a little outdated
```suggestion
        kubectl apply -f 'https://raw.githubusercontent.com/sighupio/fury-kubernetes-monitoring/v3.1.0/katalog/prometheus-operator/crds/0servicemonitorCustomResourceDefinition.yaml'
        kubectl apply -f 'https://raw.githubusercontent.com/sighupio/fury-kubernetes-monitoring/v3.1.0/katalog/prometheus-operator/crds/0prometheusruleCustomResourceDefinition.yaml'
```

2024-04-18 13:16 UTC, ralgozino commented on katalog/tests/calico/tigera.sh
> +# Copyright (c) 2022 SIGHUP s.r.l All rights reserved.
```suggestion
# Copyright (c) 2024-present SIGHUP s.r.l All rights reserved.
```

2024-04-22 14:39 UTC, nutellinoit commented
Done ✅ , merging

2024-04-22 14:40 UTC, merged