fix(calico): Added kubernetesProvider and nonPrivileged configurations
sighupio/fury-kubernetes-networking pull request #83
Opened 2024-10-14 14:32 UTC by smerlos

This PR addresses #82 by adding specific configurations for Calico in EKS. The issue was related to panic and sysctl errors, especially:
``` bash
2024-10-12 12:09:47.350 [PANIC][9460] felix/table.go 784: iptables-legacy-save command failed after retries ipVersion=0x4 table="raw"
2024-10-12 12:09:48.485 [ERROR][9510] felix/int_dataplane.go 2065: Failed to set IPv4 forwarding sysctl error=open /proc/sys/net/ipv4/ip_forward: read-only file system
```

**Changes:**

- Added kubernetesProvider: Specifies the Kubernetes platform provider (EKS), allowing automatic provider-specific configurations.

- Added nonPrivileged: Ensures Calico runs in non-privileged mode as a non-root user where possible.

2024-10-14 15:58 UTC, ralgozino commented
> * Added nonPrivileged: Ensures Calico runs in non-privileged mode as a non-root user where possible.

but you set this to `Disabled`, so IT IS running as root, is this what you wanted?

2024-10-14 16:54 UTC, ralgozino requested changes
as per my previous comment

2024-10-14 17:19 UTC, smerlos commented
> > * Added nonPrivileged: Ensures Calico runs in non-privileged mode as a non-root user where possible.
> 
> but you set this to `Disabled`, so IT IS running as root, is this what you wanted?


---

Thank you for your comment. As per the issue discussed in #82  and the logs shared in the description of the PR, the workload requires root privileges to execute correctly. Therefore, it is necessary to explicitly run it as root in this case.

2024-10-22 09:08 UTC, nutellinoit approved these changes
LGTM!

2024-11-14 15:09 UTC, merged